# Generated by Django 3.2.3 on 2023-09-15 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_tagsrecipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsamount',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_in_recipe', to='recipes.ingredients'),
        ),
        migrations.AlterField(
            model_name='ingredientsamount',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_with_ingredient', to='recipes.recipes'),
        ),
    ]
