# Generated by Django 3.2.3 on 2023-09-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20230923_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsamount',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='cooking_time',
            field=models.PositiveIntegerField(),
        ),
    ]
