# Generated by Django 3.2.3 on 2023-09-23 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20230923_2018'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TagsRecipe',
        ),
    ]
