# Generated by Django 3.2.3 on 2023-09-30 21:37

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_auto_20230929_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientamount',
            name='amount',
            field=models.PositiveIntegerField(validators=[recipes.models.validate_positive_int]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[recipes.models.validate_positive_int], verbose_name='Время приготовления'),
        ),
    ]
